/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storemanagerguiview;

import controller.Backend_DAO_List;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import model.HardwareProduct;
import model.Product;
import model.Product.type;
import model.SotfwareProduct;

/**
 *
 * @author User
 */
public class AddNewProductForm extends javax.swing.JFrame {
//איתחול ה 
//comboBox
// להגדיר אוביקט של המודל מסוג ה
//ENUM
DefaultComboBoxModel <model.Product.type> Tayps;

   //הגדרת אוביקט מסוג האינם
    DefaultComboBoxModel<type> allTayes;
   //מופע שיהיה מוכר גם בקלאס הזה
    ManageCatalogForm _ManageCatalogForm;
    
    public AddNewProductForm(ManageCatalogForm aThis) {
        //הכנסת הערכים מהאינם לקומבו 
        allTayes = new DefaultComboBoxModel<>(type.values());  
        //בונה את הטופס מקצה את הפקדים מסדרת ומאתחלת אותם
        initComponents();
        //איתחול הקומבו בפעם הראשונה ל מי שנמצא במקום ה אפס באינם
        jComboBox1.setSelectedIndex(0);
        //הכנסת הזיס למשתנה
        _ManageCatalogForm=aThis;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOtherField = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeseription = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPrice = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtVariable = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIDProduct = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(allTayes);
        jComboBox1.setName("cmbProduct"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Product name");

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Description");

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Price");

        lblOtherField.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        lblOtherField.setForeground(new java.awt.Color(204, 0, 51));
        lblOtherField.setText("Variable");
        lblOtherField.setName("lblOtherField"); // NOI18N

        txtName.setName("textName"); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtName);

        jScrollPane2.setName(""); // NOI18N

        txtDeseription.setName("TextDescription"); // NOI18N
        txtDeseription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeseriptionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDeseription);

        jScrollPane3.setName("TextPrice"); // NOI18N

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtPrice);

        jScrollPane4.setName("TextVariable"); // NOI18N

        txtVariable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVariableKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtVariable);

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Enter product information ");

        jButton1.setBackground(new java.awt.Color(153, 0, 51));
        jButton1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("IDProduct");

        txtIDProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDProductKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(lblOtherField)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4))
                                .addGap(27, 27, 27)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtIDProduct))
                                .addGap(37, 37, 37)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDProduct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOtherField))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//שיוני הטקסט לפי מה שחזר מהפונקציה
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

   if(isInHardwareMode())
       lblOtherField.setText("Warrenty Period");
   else
      lblOtherField.setText("Number of Users");  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private boolean isInHardwareMode(){
        //מביא לי מה יש בקומבו אם זה הרדוואר יחזיר טרו
      return jComboBox1.getSelectedItem().equals(type.Hardware);
    }
    
   

 
    
    
    //הוספה
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            //לא עושים כך  וכאן את הקוד אלא אם כן אנחנו רשמנו את העיצוב
//            //בדיקת תקינות לשם
//            txtName.addKeyListener(new KeyAdapter() {
//
//                @Override
//                public void keyTyped(KeyEvent e) {
//                    if(Character.isDigit(e.getKeyChar()))
//                    e.consume();
//                }
//
//            });
//
//            //בדיקת תקינות לתיאור המוצר
//            txtDeseription.addKeyListener(new KeyAdapter() {
//
//                @Override
//                public void keyTyped(KeyEvent e) {
//                    if(Character.isDigit(e.getKeyChar()))
//                    e.consume();
//                }
//
//            });
//            //בדיקת תקינות למחיר
//            txtPrice.addKeyListener(new KeyAdapter() {
//
//                @Override
//                public void keyTyped(KeyEvent e) {
//                    if(!Character.isDigit(e.getKeyChar()))
//                    e.consume();
//                }
//
//            });
            //אם ה קוד לא טוב
            if(txtIDProduct.getText().length()==0)
                throw  new Exception("ID is not good, Enter a ID");
            //אם השם לא טוב
            if(txtName.getText().length()==0)
            throw  new Exception("Name is not good, Enter a name");
            //אם התיאור לא טוב
            if(txtDeseription.getText().length()==0)
            throw  new Exception("Deseription is not good, Enter a Deseription");
            //אם המחרי לא טוב
            if(txtPrice.getText().length()==0)
            throw  new Exception("Price is not good, Enter a Price");
            
            Product newProduct=null;
            if(isInHardwareMode()){
                newProduct=new HardwareProduct();//הקצאה לאוביקט
                 //מילוי השדות
                ((HardwareProduct)newProduct).setWarrantyPeriod(Integer.parseInt(txtVariable.getText().trim()));
            }
            
            else{
              newProduct=new SotfwareProduct();
              //מילוי השדות
             ((SotfwareProduct)newProduct).setNumberOfUsers(Integer.parseInt(txtVariable.getText().trim()));
            }

            //מילוי שדות
            //*************************
            newProduct.setId(Long.parseLong(txtIDProduct.getText().trim()));
            newProduct.setName(txtName.getText());
            newProduct.setDescription(txtDeseription.getText());
            newProduct.setPricePerUnit(Float.parseFloat(txtPrice.getText()));
           //הוספת המוצר 
           Backend_DAO_List.getBdl_singleton().AddProduct(newProduct);

            //ריענון מוצרים
            _ManageCatalogForm.RefreshProductList();

            //הדפסת הודעה מתאימה
            JOptionPane.showMessageDialog
            (AddNewProductForm.this,
                "Produc successfully added",
                "message",
                JOptionPane.INFORMATION_MESSAGE);

            //ריקון שדות
            txtDeseription.setText(" ");
            txtName.setText(" ");
            txtPrice.setText(" ");
            txtVariable.setText(" ");
            txtIDProduct.setText(" ");
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog
            (AddNewProductForm.this,
                ex.getMessage(),
                "message",
                JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

     //בדיקות תקינות
    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
         //בדיקה של השם
         if(Character.isDigit(evt.getKeyChar()))
         evt.consume();
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtDeseriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeseriptionKeyTyped
       //בדיקת התיאור
       if(Character.isDigit(evt.getKeyChar()))
          evt.consume();
    }//GEN-LAST:event_txtDeseriptionKeyTyped

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
       //בדיקת המחיר
       if(!Character.isDigit(evt.getKeyChar()))
          evt.consume();
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtIDProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDProductKeyTyped
        //בדיקת הקוד מוצר
         if(!Character.isDigit(evt.getKeyChar()))
          evt.consume();
    }//GEN-LAST:event_txtIDProductKeyTyped

    private void txtVariableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVariableKeyTyped
       //בדיקה של השדה האחרון
        if(!Character.isDigit(evt.getKeyChar()))
          evt.consume();
    }//GEN-LAST:event_txtVariableKeyTyped


   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblOtherField;
    private javax.swing.JTextPane txtDeseription;
    private javax.swing.JTextField txtIDProduct;
    private javax.swing.JTextPane txtName;
    private javax.swing.JTextPane txtPrice;
    private javax.swing.JTextPane txtVariable;
    // End of variables declaration//GEN-END:variables

    private void RefreshProductList() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
